### ISSUE TITLE
Error actualitzant la versió dels subprocessos important tipus d'expedient

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/helium#1269]
Es reporta que quan s'importa un tipus d'expedient amb diferents definicions de procés i subprocessos  aquests no s'actualitzen tots correctament. S'ha de revisar la importació per a que tots els subprocessos importats incrementin la versió.
 
 En el correu de l'error s'inclou el següent exemple:

 Situació abans de la importació:

 
![image](https://user-images.githubusercontent.com/17267008/52857466-88326380-3127-11e9-9601-5c7d8c773e92.png)

Sancionadors_GS (v222) crida a Notificacions_GS (v157), Recursos_GS (v76) i Fraccionament_GS (v79)

![image](https://user-images.githubusercontent.com/17267008/52857488-97b1ac80-3127-11e9-9e36-fa63dc9a0c9c.png)

 Importació:

![image](https://user-images.githubusercontent.com/17267008/52857504-a8622280-3127-11e9-8430-4b3af21730b8.png)

Situació després de la importació:

![image](https://user-images.githubusercontent.com/17267008/52857518-b617a800-3127-11e9-9dd0-f176ec2a5ba0.png)

Sancionadors_GS (v223) crida a Notificacions_GS (v158, com ha de ser), Recursos_GS (v76, no l'ha incrementat) i Fraccionament_GS (v79, no l'ha incrementat):

![image](https://user-images.githubusercontent.com/17267008/52857549-c7f94b00-3127-11e9-8b1a-ea8faec0cb7f.png)

**Comment by ssoler-dgtic** [comment]
Saludos

Si l'errada no us apareix fent directament una importació, provau d'executar prèviament l'esborrat de defincions de procés "intermitges" no utilitzades amb la utilitat adient que es va desenvolupar fa un any i mig.

Sebastià Soler Chacartegui
Cap de Secció
Direcció General de Desenvolupament Tecnològic




Josep Gayà ---15/02/2019 13:44:49--- Es reporta que quan s'importa un tipus d'expedient amb diferents definicions de procés i subprocessJosep Gayà ---15/02/2019 13:44:49--- Es reporta que quan s'importa un tipus d'expedient amb diferents definicions de procés i subprocess

De:	Josep Gayà <notifications@github.com>
Per a:	GovernIB/helium <helium@noreply.github.com>
a/c:	Subscribed <subscribed@noreply.github.com>
Data:	15/02/2019 13:44
Assumpte:	[GovernIB/helium] Error actualitzant la versió dels subprocessos important tipus d'expedient (#1269)



Es reporta que quan s'importa un tipus d'expedient amb diferents definicions de procés i subprocessos aquests no s'actualitzen tots correctament. S'ha de revisar la importació per a que tots els subprocessos importats incrementin la versió.
En el correu de l'error s'inclou el següent exemple:
Situació abans de la importació:

Sancionadors_GS (v222) crida a Notificacions_GS (v157), Recursos_GS (v76) i Fraccionament_GS (v79)

Importació:

Situació després de la importació:

Sancionadors_GS (v223) crida a Notificacions_GS (v158, com ha de ser), Recursos_GS (v76, no l'ha incrementat) i Fraccionament_GS (v79, no l'ha incrementat):

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by josepg-limit** [comment]
Es crea una comnada jbpm per actualitzar els nodes de tipus process state per a que apuntin a la versió de la definició de procés correcta.
